feat(HACBS-852): add script to copy applications
konflux-ci/release-service-utils pull request #1
Opened 2022-07-27 12:53 UTC by davidmogar

The new script allows to copy applications (and their components) to a target namespace. This will be used to create copies of the dev applications (and components) into the managed namespaces.

Signed-off-by: David Moreno García <damoreno@redhat.com>

2022-07-27 13:19 UTC, johnbieren requested changes

2022-07-27 13:19 UTC, johnbieren commented on hacbscopy.sh
> +    echo "  --all             copy resources from all namespaces"
Can we expand on this help a little bit? As a user, I don't understand. Copy all resources from all namespaces? On line 96 we say all applications, let's do that here too

2022-07-27 13:19 UTC, johnbieren commented on hacbscopy.sh
> +    echo -e "\nCopy all applications and related resources from one workspace to another.\n"
Isn't "related resources" just components?

2022-07-27 13:19 UTC, johnbieren commented on hacbscopy.sh
> +        echo "Only the target workspace positional argument is required"
I don't like "required" here. IIUC, this is checking you didn't pass too many arguments. Maybe `s/required/accepted` or "Passing more than the target workspace positional argument is not supported"

2022-07-27 13:19 UTC, johnbieren commented on hacbscopy.sh
> +    echo -e "\nCopy all applications and related resources from one workspace to another.\n"
This is also the only line of the help ending in a period

2022-07-27 13:19 UTC, johnbieren commented on hacbscopy.sh
> +    readarray -t components < <(kubectl get component -n "$1" -o jsonpath="{range .items[?(@.spec.application==\"$2\")]}{.metadata.name}{\"\n\"}{end}")
I think future devs or users of this script would appreciate a comment for this line to say what is going on

2022-08-01 08:18 UTC, davidmogar commented on hacbscopy.sh
> +    echo -e "\nCopy all applications and related resources from one workspace to another.\n"
Regarding the period, I'm copying the format of `getopt` help. The description has a period.

2022-08-01 08:20 UTC, davidmogar commented on hacbscopy.sh
> +        echo "Only the target workspace positional argument is required"
Changed to `Only one positional argument (target workspace) is accepted`. What do you think?

2022-08-01 12:54 UTC, johnbieren commented on hacbscopy.sh
> +        echo "Only the target workspace positional argument is required"
works for me

2022-08-16 19:41 UTC, johnbieren approved these changes

2022-08-17 08:38 UTC, theflockers approved these changes
Some comments added as suggestions. Overall LGTM.

2022-08-17 08:38 UTC, theflockers commented on hacbscopy.sh
> +        echo "Copying component '$component' to namepsace '$WORKSPACE'"
s/namepsace/namespace/g

2022-08-17 08:38 UTC, theflockers commented on hacbscopy.sh
> +    echo -e "\n  -h, --help        display this help"
You could use just one echo here to not create unnecessary procs just to output a text. You could also use `cat` instead. Just a suggestion as well.

```
$ cat <<EOF 
crazy long text
EOF
```

2022-08-17 12:24 UTC, johnbieren commented on hacbscopy.sh
> +        echo "Copying component '$component' to namepsace '$WORKSPACE'"
can't believe I missed this one

2022-08-17 12:25 UTC, johnbieren commented on hacbscopy.sh
> +    application=$(echo "$1" | cut -d '/' -f 2)
As someone who has certainly spent time in bash and saw that notation in Jon's PR and had no idea what it did, I am in favor of the cut method. Very much just my opinion, but I think cut is more commonly understood and easier to read

2022-08-22 12:20 UTC, davidmogar commented on hacbscopy.sh
> +    echo -e "\n  -h, --help        display this help"
True! I like to avoid using that though. It fucks up indentation :sweat_smile: 

Same function would be:
```
show_help() {
    echo <<EOF
Usage:
...
EOF
}
```

2022-08-22 12:22 UTC, davidmogar commented on hacbscopy.sh
> +    application=$(echo "$1" | cut -d '/' -f 2)
I didn't know this trick until recently actually. I also prefer the cut. Using that is like dancing with a wizard and waking up naked and realizing you are a lynx now.

2022-08-22 12:23 UTC, davidmogar commented on hacbscopy.sh
> +        echo "Copying component '$component' to namepsace '$WORKSPACE'"
Good eyes! Fixed.

2022-08-22 12:23 UTC, merged