feat(hacbs_2226): create a task to clone a repo and update files given fileUpdates for repo
konflux-ci/release-service-utils pull request #40
Opened 2023-07-10 08:36 UTC by theflockers

This PR adds the installation of the `glab` tool and functions to handle gitlab repos.

2023-07-11 11:51 UTC, mmalina commented on functions/gitlab
> +init_gitlab $1
The way this is set up, I would expect this file to only contain function definitions, so a user of this would source the file (`source functions/gitlab`) and then run whichever functions they wish. But here we call one of the functions already - that doesn't seem right. Same way as a python script shouldn't run anything if you merely import it.

So I think this line should be removed and the `init_gitlab` function should be called in the task where this is used.

2023-07-11 11:51 UTC, mmalina commented on functions/gitlab
> +    echo -e "\t~$ export ACCESS_KEY=<github key>\n\t~$ . gitlab <gitlab host>"
Any reason why the lines above are separate, but here two lines are combined (with `\n`)? I think it would improve readability if all the lines were separate.

2023-07-11 11:51 UTC, mmalina commented on functions/gitlab
> +show_help() {
Once the function file is loaded, these functions will be globally available in the given shell session. I think it would be better to have a more specific name, e.g. `gitlab_usage`.

2023-07-11 11:51 UTC, mmalina commented on functions/gitlab
> +    echo -e "\t~$ export ACCESS_KEY=<github key>\n\t~$ . gitlab <gitlab host>"
Also, here it says `ACCESS_KEY`, but in the init function, I can see that `ACCESS_TOKEN` is used.

2023-07-11 11:51 UTC, mmalina commented on functions/gitlab
> +  [ -z "${GIT_AUTHOR_NAME}" -o -z "${GIT_AUTHOR_EMAIL}" ] && show_help && return
I think this should return a non-zero code in such case. Same applies to the other ones below as well.

2023-07-11 14:01 UTC, johnbieren reviewed
Can you change the commit title? I know that is the ticket description, but this commit is just about adding functions to interact with gitlab. It doesn't have anything to do with tekton tasks

2023-07-11 15:29 UTC, theflockers commented on functions/gitlab
Misread your last phrase. I had the impression that it had only executables, not include files. If that is the case, indeed. I can move it to utils.

2023-07-11 15:30 UTC, theflockers commented on functions/gitlab
> +    glab mr create --title "chore: fileUpdates changes" -b $HEAD --description "chore: fileUpdates changes" | \
I noticed (after having a bunch of MR open) that I will also need to add some unique identification in the title. @mmalina @johnbieren . I will change this as well.

2023-07-13 12:34 UTC, mmalina commented on functions/gitlab
> +init_gitlab $1
I think this concern is still valid. The file was moved to `utils/`, but it's called `gitlab-functions` and it says that it's a library at the top of the file. So I still believe it shouldn't really do anything upon being sourced.

2023-07-13 12:41 UTC, mmalina commented on functions/gitlab
> +show_help() {
It's better now. But on related topic, I think it would be nice if all the functions had a common prefix, say `gitlab_`, that way it's clearer that it all comes from this one place - especially when looking at the script that uses the functions in the tekton task.

2023-07-13 13:24 UTC, theflockers commented on functions/gitlab
> +    echo -e "\t~$ export ACCESS_KEY=<github key>\n\t~$ . gitlab <gitlab host>"
No actual reason for the separation. Just missed to format it properly. Fixed also to `ACCESS_TOKEN`  instead.

2023-07-13 15:26 UTC, mmalina commented on functions/gitlab
> +    echo -e "\t~$ export ACCESS_KEY=<github key>\n\t~$ . gitlab <gitlab host>"
cool, thanks.

2023-07-13 15:27 UTC, mmalina commented on functions/gitlab
> +show_help() {
Yeah, it would probably make sense to have a separate one for `git-` functions.

2023-07-13 18:24 UTC, johnbieren submitted a review, later dismissed
I'm good with the code once Martin's concerns are addressed

2023-07-17 09:01 UTC, theflockers commented on functions/gitlab
> +init_gitlab $1
done. Now the init is called in the task.

2023-07-17 09:02 UTC, theflockers commented on functions/gitlab
> +show_help() {
done. Added `git-functions` file.

2023-07-17 11:29 UTC, mmalina commented on utils/git-functions
> +    git add . && git commit -m "$COMMIT_MSG"
You can just do `git commit -a -m "$COMMIT_MSG"` and the `git add .` is not needed.

If you did want to do this separately for some reason, I would suggest just running each command on a separate line - there is no reason to combine the two this way.

2023-07-17 11:29 UTC, mmalina commented on utils/git-functions
> +    test ! -d $REPO_DIR && git -c http.sslVerify=false clone $CLONE_URL
Based on this, I assume $REPO_DIR is required to exist already. Why is that the case? The `git clone` will create it for you, right?

Also, why are specifically these two commands combined with `&&`? If the test fails, the whole function will hopefully fail and exit anyway, right? Also, in general in such tests it's usually nicer to use `if` and explicitly print what's wrong, like:
```sh
if ! [ -d $REPO_DIR ]
then
    echo Error: $REPO_DIR does not exist.
    return 1
fi
```

2023-07-17 11:29 UTC, mmalina commented on utils/git-functions
> +    git remote set-url origin $CLONE_URL
Will this not be done automatically? AFAIK, when you clone a new repo, you automatically have a remote called `origin` with the url set to what you cloned. Is this not the case here? Perhaps because of the non-standard url with oauth2? If that's the case, I think it warrants a comment.

2023-07-17 11:29 UTC, mmalina commented on utils/gitlab-functions
> +    glab config set skip_tls_verify true --host $gitlab_host
Again, we should not have to skip ssl/tls verification. And if we can get rid of that, then this function is probably not needed, since it would only call one command, right?

2023-07-17 11:29 UTC, mmalina commented on utils/gitlab-functions
> +    glab mr create --title "${TITLE}" -b ${HEAD} --description "${DESCRIPTION}" | \
Hmm, I'm starting to wonder if we need any gitlab functions at all - if we remove `gitlab_init` and `gitlab_usage` as I suggested elsewhere. And `gitlab_auth` too. Then all we're left with is this `glab mr create` wrapper which can easily be done inline.

Do we at least anticipate to call this from multiple places? I wonder what you and others think.

2023-07-17 11:35 UTC, theflockers commented on utils/git-functions
> +    git add . && git commit -m "$COMMIT_MSG"
No reason. I will change to use `-a` instead.

2023-07-17 11:42 UTC, theflockers commented on utils/git-functions
> +    git -c http.sslVerify=false push origin $BRANCH
`glab` does not like the certificate.  I will search where I might pull the CA to add to the image.

2023-07-17 11:52 UTC, theflockers commented on utils/git-functions
> +    test ! -d $REPO_DIR && git -c http.sslVerify=false clone $CLONE_URL
Thanks for notice this. This is actually a test leftover.

In my tests I was listing the same repo twice - so each cycle it would need to clone the repo again. If the dir exists, git fails and the script exits, which is not desirable.

This is not the case anymore because now the script always cleans up the workspace after the MR is created, so for the next clone it starts freshly. I will remove the `test ! -d`

2023-07-17 11:54 UTC, theflockers commented on utils/git-functions
> +    git remote set-url origin $CLONE_URL
I have to set this otherwise git will expose the credentials when pushing.

2023-07-17 12:01 UTC, theflockers commented on utils/gitlab-functions
> +    glab config set skip_tls_verify true --host $gitlab_host
same problem as above. I will find out where I can fetch the CA and add it to the image.

2023-07-17 12:08 UTC, theflockers commented on utils/gitlab-functions
> +    glab mr create --title "${TITLE}" -b ${HEAD} --description "${DESCRIPTION}" | \
The `gitlab_init` and `gitlab_usage` it is just a way to let the user know that all vars required are set. 

The end goal was having something that can be reusable otherwise I would just leave everything in line in the task. 

If all this looks too much, I am (not so) happy to make it simpler.

2023-07-17 13:03 UTC, theflockers commented on utils/git-functions
> +    git -c http.sslVerify=false push origin $BRANCH
done. CA added and ssl verify bypass removed.

2023-07-17 13:04 UTC, theflockers commented on utils/git-functions
> +    test ! -d $REPO_DIR && git -c http.sslVerify=false clone $CLONE_URL
`test ! -d` and ssl verify bypass removed.

2023-07-17 13:10 UTC, theflockers commented on utils/git-functions
> +    git remote set-url origin $CLONE_URL
I will remove it. It looked to build old builds, it happened only on github (my first PR had it). If we need it in the future, we can add this again.

2023-07-17 13:14 UTC, johnbieren commented on utils/gitlab-functions
> +    glab mr create --title "${TITLE}" -b ${HEAD} --description "${DESCRIPTION}" | \
I think we should keep a gitlab functions file. Once we are doing things like automerging or whatever, it will likely be different between gitlab and github

2023-07-17 13:21 UTC, theflockers commented on utils/gitlab-functions
> +gitlab_init() {
BTW, should we conform to a styleguide? Maybe https://google.github.io/styleguide/shellguide.html

2023-07-17 13:30 UTC, theflockers commented on Dockerfile
> +ADD https://certs.corp.redhat.com/certs/2015-IT-Root-CA.pem https://certs.corp.redhat.com/certs/2022-IT-Root-CA.pem /etc/pki/ca-trust/source/anchors/
Not  sure TBH. Anyhow the CA has only public information as the public key, for instance.

2023-07-17 13:32 UTC, theflockers commented on utils/gitlab-functions
> +    glab mr create --title "${TITLE}" -b ${HEAD} --description "${DESCRIPTION}" | \
+1. I prefer to keep them.

2023-07-17 13:48 UTC, mmalina commented on functions/gitlab
> +init_gitlab $1
Thanks.

2023-07-17 13:50 UTC, mmalina commented on utils/gitlab-functions
> +gitlab_init() {
Thanks for linking Google's style guide. It definitely looks nice. Not sure if we need to strictly follow it, we can discuss later.

2023-07-17 13:53 UTC, mmalina commented on utils/gitlab-functions
> +gitlab_init() {
> Just made a simpler comment in the top of the two files. I think it looks better now. Please take a look.

I agree it's better - at least it's consistent now. But I think it should still at least say that `glab` is required to be installed. Don't you agree?

2023-07-17 13:55 UTC, mmalina commented on Dockerfile
> +ADD https://certs.corp.redhat.com/certs/2015-IT-Root-CA.pem https://certs.corp.redhat.com/certs/2022-IT-Root-CA.pem /etc/pki/ca-trust/source/anchors/
Yep, I agree this should be fine - it's done in other places as well.

2023-07-17 13:55 UTC, mmalina commented on utils/git-functions
> +    git -c http.sslVerify=false push origin $BRANCH
Awesome, thanks!

2023-07-17 13:56 UTC, mmalina commented on utils/git-functions
> +    test ! -d $REPO_DIR && git -c http.sslVerify=false clone $CLONE_URL
Great, thanks.

2023-07-17 13:56 UTC, mmalina commented on utils/git-functions
> +    git add . && git commit -m "$COMMIT_MSG"
Thanks.

2023-07-17 13:57 UTC, mmalina commented on utils/git-functions
> +    git remote set-url origin $CLONE_URL
Cool.

2023-07-17 13:59 UTC, mmalina commented on utils/gitlab-functions
> +    glab mr create --title "${TITLE}" -b ${HEAD} --description "${DESCRIPTION}" | \
Alright.

2023-07-17 14:13 UTC, theflockers commented on utils/gitlab-functions
> +gitlab_init() {
Sure, I agree. I actually forgot to add the info. Done now.

2023-07-17 14:31 UTC, mmalina commented on utils/gitlab-functions
> +gitlab_init() {
Cool, thanks.

2023-07-17 14:39 UTC, mmalina commented on utils/git-functions
> +    CLONE_URL="https://oauth2:${ACCESS_TOKEN}@${REPO_URL#*://}"
s/REPO_URL/REPOSITORY/ , right? `REPO_URL` doesn't seem to be defined anywhere.

2023-07-18 09:05 UTC, theflockers commented on utils/git-functions
> +    CLONE_URL="https://oauth2:${ACCESS_TOKEN}@${REPO_URL#*://}"
Fixed! Please take a look.

2023-07-18 10:30 UTC, mmalina requested changes
@theflockers one last thing: Can you alter the commit message so that the title fits and is not split? I think the limit is 72 characters. Also, can you mention that red hat cert was added?

2023-07-18 11:14 UTC, mmalina approved these changes

2023-07-18 11:21 UTC, merged